---
- hosts: all
  become: yes
  remote_user: ubuntu

  tasks:
  - name: Update OS
    apt:
      update_cache: yes

  - name: Install Nginx
    apt:
      name: nginx
      state: present

  - name: Copy Website Files
    copy:
      src: index.html
      dest: /var/www/html/
      mode: '0644'
